### ISSUE TITLE
Add external_id for repository versions into ocl_web

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/DATIM-Metadata-Project#70]
The external_id attribute is already supported in the API for source versions and collection versions. We want to store the DHIS2 datasetid in the repository version external_id field.

**Comment by davetrig** [comment]
@paynejd , I think you may be mistaken about the external id being "already supported".  The external_id field in the source version and collection version is currently used to store the external_id of the version's respective source or collection.

If we want to store an additional external_id for the version itself, we'll have to add a new field.

**Comment by davetrig** [comment]
Coding is complete for adding a new field, version_external_id for source and collection versions.  Pull requests are submitted under both oclapi and ocl_web projects.

@paynejd & @rkorytkowski: I haven't created any integration tests for these changes yet; perhaps we can discuss what tests you think are appropriate after tomorrow's stand-up.

**Comment by paynejd** [comment]
Adding @rkorytkowski to this ticket for Review/QA

**Comment by rkorytkowski** [comment]
Both PRs merged. An api test is needed showing the new field can be saved and read from db.

**Comment by rkorytkowski** [comment]
When I setup a new oclapi environment i.e. do:
```
docker-compose down -v 
docker-compose up
```
I get 
```
api_1     | Importing Lookup Values
mongo_1   | 2017-09-06T09:41:14.731+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.5:55004 #5 (3 connections now open)
api_1     | NameError: global name 'version_external_id' is not defined
```
And no initial data is available when the server starts.

**Comment by rkorytkowski** [comment]
Tests are failing as well https://ci.openmrs.org/browse/OCL-OA-RIT-51

I'll revert your PR and wait for fixes.

**Comment by davetrig** [comment]
Pull request submitted, includes integration tests and should fix the errors you saw.

**Comment by rkorytkowski** [comment]
Tests are still failing, see https://ci.openmrs.org/browse/OCL-OA-RIT-56/log

I'm reverting your changes again.

**Comment by davetrig** [comment]
Ok, I don't remember seeing that when I ran it, but I must have missed it.  I'm on it.

**Comment by davetrig** [comment]
@rkorytkowski I'm just not seeing those errors when I run the integration tests.  I'm attaching the output from the run of integration tests.  What am I missing?
[integration_tests.log.txt](https://github.com/OpenConceptLab/DATIM-Metadata-Project/files/1301166/integration_tests.log.txt)

**Comment by davetrig** [comment]
@rkorytkowski I've also tried:

docker-compose down -v
docker-compose up
docker-compose run ocl_api python manage.py test integration_tests --configuration=Dev

...and I still do not get the error you saw.

**Comment by davetrig** [comment]
@rkorytkowski Can you verify that the changes to oclapi/models.py were properly merged when you got this error? I cannot continue with this ticket until we figure out why I can't replicate this error.

**Comment by rkorytkowski** [comment]
I merged in your changes locally instead of using github UI and tests passed for me locally. I pushed them to master and jetstream branches and tests passed as well on both CIs. It seems to have been an issue with an automatic merge, which is strange... Anyway good thing it is working now.
